/* Static SVG renderer uses the same engine and celestial artwork as the page.
 * This is scene QA, NOT a browser screenshot or CSS/interactivity verification. */
const fs=require('fs'),path=require('path'),C=require('../src/universe.js'),V=require('../src/visuals.js');
const root=path.resolve(__dirname,'..'),graph=require('../../../research/graph.json');
const m=C.make(graph,{anchors:require('../data/anchors.json')});C.simulation(m).tick(350);
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function render(t,overview=false){C.updateOrbits(m,t);const w=1440,h=940,k=overview?.12:.91,tx=overview?w/2+390*k:w/2,ty=overview?h/2+160*k:h/2+35;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><defs>${V.defs()}</defs>${V.starfield(w,h)}<g transform="translate(${tx},${ty}) scale(${k})">`;for(const sys of m.systems){s+=`<ellipse cx="${sys.x}" cy="${sys.y}" rx="${sys.radius*1.9}" ry="${sys.radius*1.1}" fill="url(#nebula-purple)"/>`;if(overview)s+=`<g transform="translate(${sys.x},${sys.y}) scale(${1/k})">${V.systemGlyph(sys,m.systems.indexOf(sys))}</g><text x="${sys.x}" y="${sys.y-sys.radius}" text-anchor="middle" font-family="sans-serif" font-size="${12/k}" fill="${sys.color}">${esc(sys.name.split(' · ')[0])}</text>`;}
for(const n of m.nodes)if(n.orbit){const p=m.byId.get(n.orbit.parent);s+=`<ellipse cx="${p.x}" cy="${p.y}" rx="${n.orbit.radius}" ry="${n.orbit.radius*n.orbit.tilt}" fill="none" stroke="#8495ab" stroke-opacity=".32" stroke-width=".7"/>`;}
for(const e of m.edges.filter(e=>['E02','E03'].includes(e.id))){const j=C.junction(e,m);for(const id of e.inputs){let c=C.curve(m.byId.get(id),j);s+=`<path d="M${c.a.x} ${c.a.y}Q${c.c.x} ${c.c.y} ${c.b.x} ${c.b.y}" stroke="#759cb9" fill="none" stroke-width="1" opacity=".65"/>`;}let c=C.curve(j,m.byId.get(e.output),1);s+=`<path d="M${c.a.x} ${c.a.y}Q${c.c.x} ${c.c.y} ${c.b.x} ${c.b.y}" stroke="#8eaac0" fill="none" marker-end="url(#arrow)"/><g transform="translate(${j.x} ${j.y})"><path d="M0-10L10 0L0 10L-10 0Z" fill="#122139" stroke="#8eb5cd"/><text text-anchor="middle" y="4" font-size="11" fill="#bedced">∧</text></g>`;}
for(const n of m.nodes){s+=`<g transform="translate(${n.x} ${n.y})">${V.body(n,C.orbitIds.indexOf(n.id))}`;if(!overview&&n.group==='solar'&&n.kind!=='moon')s+=`<text x="0" y="${n.r+26}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#a7b4c6">${esc(n.id==='R02'?'RLEB · PPA':n.id)}</text>`;s+='</g>';}
s+='</g><text x="42" y="48" font-family="sans-serif" font-size="12" fill="#e4bb7b" letter-spacing="4">RESEARCH COSMOS</text><text x="42" y="76" font-family="sans-serif" font-size="11" fill="#677f99">Shared engine / static scene preview · t = '+t+'s · not a browser screenshot</text></svg>';fs.writeFileSync(path.join(root,'qa',overview?'overview.svg':`solar-${t}.svg`),s);}
render(0);render(12);render(0,true);console.log('Wrote shared-renderer static scene SVGs.');
