'use strict';
const fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const C=require('../src/universe.js');const graph=JSON.parse(fs.readFileSync(path.join(__dirname,'../../../research/graph.json')));const saved=require('../data/anchors.json');
const m=C.make(graph,{anchors:saved}),sim=C.simulation(m);sim.tick(350);let tests=0;function test(name,f){f();tests++;console.log('PASS '+name)}
test('exact graph and conjunctive endpoints are preserved',()=>{assert.deepEqual(m.graph,graph);assert.equal(m.nodes.length,graph.nodes.length);assert.equal(m.edges.length,graph.edges.length);assert.deepEqual(m.edges.find(e=>e.id==='E02').inputs,['D02','COV','D04']);assert.deepEqual(m.edges.find(e=>e.id==='E03').inputs,['R01','CMP','LOC']);});
test('D3 forces actually relax coincident nonorbital objects',()=>{let x=C.make(graph),a=x.byId.get('EX-ROT'),b=x.byId.get('EX-DIAG');a.x=b.x=1000;a.y=b.y=1000;a.ax=b.ax=1000;a.ay=b.ay=1000;let s=C.simulation(x);s.tick(300);assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>a.r+b.r+10);});
test('eight core planets and six genuine graph-node satellites',()=>{assert.deepEqual(m.nodes.filter(n=>n.kind==='planet').map(n=>n.id),C.orbitIds);const ids=new Set(graph.nodes.map(n=>n.id));for(const n of m.nodes.filter(n=>n.orbit)){assert.ok(ids.has(n.id));assert.ok(ids.has(n.orbit.parent));}});
test('binary and Gaussian mathematical models stay separate',()=>{assert.equal(m.byId.get('M-COND').group,'binary');assert.equal(m.byId.get('G-COND').group,'gaussian');assert.notEqual(m.byId.get('COND-EB').group,m.byId.get('G-COND-EB').group);});
test('different orbital periods produce actual moving positions',()=>{C.updateOrbits(m,0);const p=m.byId.get('D01'),old={x:p.x,y:p.y};C.updateOrbits(m,4);assert.ok(Math.hypot(p.x-old.x,p.y-old.y)>30);assert.notEqual(p.orbit.period,m.byId.get('R01').orbit.period);});
test('zero time step is an exact orbital/route pause',()=>{C.updateOrbits(m,17);let before=m.nodes.map(n=>[n.id,n.x,n.y]);C.updateOrbits(m,17);assert.deepEqual(before,m.nodes.map(n=>[n.id,n.x,n.y]));});
test('600 sampled seconds without solar body intersections',()=>{for(let t=0;t<600;t+=.25){C.updateOrbits(m,t);const a=m.nodes.filter(n=>['planet','moon','sun'].includes(n.kind));for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)assert.ok(Math.hypot(a[i].x-a[j].x,a[i].y-a[j].y)>=a[i].r+a[j].r,`${t}: ${a[i].id}/${a[j].id}`);}});
test('force collision separates nonorbital bodies in settled graph',()=>{const a=m.nodes.filter(n=>!n.orbit&&n.kind!=='sun');for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)assert.ok(Math.hypot(a[i].x-a[j].x,a[i].y-a[j].y)>=a[i].r+a[j].r,`${a[i].id}/${a[j].id}`);});
test('growth/reorder preserve saved semantic anchors',()=>{const g=structuredClone(graph);for(let i=0;i<125;i++){g.nodes.push({id:'TEST-'+i,label:'TEST',file:'canonical/path_atlas.md'});g.edges.push({id:'TEST-E-'+i,inputs:['R01','CMP'],output:'TEST-'+i,relation:'test'});}g.nodes.reverse();g.edges.reverse();const grown=C.make(g,m);for(const n of graph.nodes)assert.deepEqual(grown.anchors[n.id],m.anchors[n.id]);const settled=C.simulation(grown);settled.tick(350);let max=0;for(const n of m.nodes.filter(n=>!n.orbit&&n.kind!=='sun')){const p=grown.byId.get(n.id);max=Math.max(max,Math.hypot(p.x-n.x,p.y-n.y));}assert.ok(max<150,`max existing node relaxation ${max}`);console.log('  existing render-position maximum local relaxation:',max.toFixed(2));});
test('deletion/restoration retain anchors and reject missing hyperedge endpoints',()=>{let g=structuredClone(graph);g.nodes=g.nodes.filter(n=>n.id!=='R01');assert.throws(()=>C.make(g,m));g=structuredClone(graph);g.nodes.pop();g.edges=g.edges.filter(e=>e.output!==graph.nodes.at(-1).id&&!e.inputs.includes(graph.nodes.at(-1).id));const removed=C.make(g,m),restored=C.make(graph,removed);assert.deepEqual(restored.anchors,m.anchors);});
test('one conjunction junction per edge with every input and true output',()=>{for(const e of m.edges){const j=C.junction(e,m);assert.ok(Number.isFinite(j.x)&&Number.isFinite(j.y));for(const id of e.inputs){const c=C.curve(m.byId.get(id),j);assert.deepEqual(C.at(c,0),{x:c.a.x,y:c.a.y});assert.deepEqual(C.at(c,1),j);}}});
test('offline HTML embeds authoritative graph and vendored D3',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const data=html.match(/id="graph-data" type="application\/json">([\s\S]*?)<\/script>/)[1];assert.deepEqual(JSON.parse(data),graph);assert.ok(html.includes('https://d3js.org v7.9.0'));assert.ok(!/<script[^>]+src="https?:/i.test(html));assert.ok(html.includes('prefers-reduced-motion'));assert.ok(html.includes("['refutes','limits'].includes"));});
console.log(`${tests} tests passed. Structural/numerical tests do not substitute for browser visual QA.`);
