(()=>{'use strict';
const C=CosmosEngine,V=CosmosVisuals,BASE=JSON.parse(document.getElementById('graph-data').textContent),anchors=JSON.parse(document.getElementById('anchor-data').textContent),$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let model=C.make(BASE,{anchors}),sim=C.simulation(model),selected={type:'node',id:'R02'},activeSystem='solar',running=!matchMedia('(prefers-reduced-motion: reduce)').matches,speed=1,routeMode='related',labelsMode=false,clock=0,last=0,frame=0,zoom=d3.zoomIdentity,dragging=false,demo=0,visibleEdges=[],routeDOM=[],nodeDOM=new Map(),systemDOM=[];
const svg=d3.select('#scene'),world=d3.select('#world'),vp=$('viewport');$('defs').innerHTML=V.defs();
function el(tag,attrs={},parent){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(parent)parent.append(e);return e;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(s){$('toast').textContent=s;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),4000);}
const zoomer=d3.zoom().scaleExtent([.075,5]).on('zoom',e=>{zoom=e.transform;world.attr('transform',zoom);refreshLOD();});svg.call(zoomer).on('dblclick.zoom',null);
function camera(x,y,k,animate=true){const t=d3.zoomIdentity.translate(vp.clientWidth/2-x*k,vp.clientHeight/2-y*k).scale(k);if(animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)svg.transition().duration(800).call(zoomer.transform,t);else svg.call(zoomer.transform,t);}
function zoomBy(factor){const target=matchMedia('(prefers-reduced-motion: reduce)').matches?svg:svg.transition().duration(250);target.call(zoomer.scaleBy,factor);}
function solar(){activeSystem='solar';camera(0,0,Math.min((vp.clientWidth-85)/1460,(vp.clientHeight-210)/820));$('home').classList.add('active');$('overview').classList.remove('active');}
function overview(){activeSystem=null;camera(-390,-160,Math.min((vp.clientWidth-90)/6600,(vp.clientHeight-160)/5950));$('overview').classList.add('active');$('home').classList.remove('active');}
function focus(id){const n=model.byId.get(id);if(!n)return;activeSystem=n.group;camera(n.x,n.y,Math.min(1.3,(vp.clientHeight-160)/650));selectNode(id);}
function systemFocus(id){const s=model.systems.find(s=>s.id===id);activeSystem=id;if(id==='solar')solar();else camera(s.x,s.y,Math.min((vp.clientWidth-100)/(s.radius*2.4),(vp.clientHeight-180)/(s.radius*1.8)));const candidates=model.nodes.filter(n=>n.group===id);let main=candidates.find(n=>['SIZE','M-FIN','M-BINARY','M-GAUSS','H02','W01','PA-WHOLE','C-MSCQ'].includes(n.id))||candidates[0];if(main)selectNode(main.id);}
function makeBackdrop(){$('nebulae').innerHTML='';$('system-labels').innerHTML='';systemDOM=[];for(const s of model.systems){el('ellipse',{cx:s.x,cy:s.y,rx:s.radius*1.9,ry:s.radius*1.1,fill:`url(#nebula-${s.id==='solar'||s.id==='markov'?'blue':'purple'})`,transform:`rotate(-22 ${s.x} ${s.y})`},$('nebulae'));if(s.id==='solar'){el('ellipse',{rx:760,ry:470,fill:'url(#corona)',opacity:'.16'},$('nebulae'));}let g=el('g',{'data-system':s.id,style:'cursor:pointer'},$('system-labels'));g.addEventListener('click',()=>systemFocus(s.id));el('text',{x:s.x,y:s.y-s.radius*.91,'text-anchor':'middle',class:'system-title'},g).textContent=s.name;el('text',{x:s.x,y:s.y-s.radius*.91+28,'text-anchor':'middle',class:'system-subtitle'},g).textContent=s.subtitle;let swirl=el('g',{'data-field':s.id,transform:`translate(${s.x},${s.y})`,opacity:s.id==='solar'?'0':'.16'},$('nebulae'));swirl.innerHTML='<g class="field-spin"><ellipse rx="150" ry="52" fill="url(#galaxy-glow)"/><path d="M-90 45C-145-10 53-87 99-31C137 15-47 84-87 24M-53-46C8-86 130-7 61 33" stroke="'+s.color+'" stroke-width="5" fill="none" opacity=".35"/></g>';const glyph=el('g',{'data-system-glyph':s.id,role:'button',tabindex:0,'aria-label':s.name+' 主题星系',style:'cursor:pointer'},$('system-labels'));glyph.innerHTML=V.systemGlyph(s,model.systems.indexOf(s));glyph.addEventListener('click',()=>systemFocus(s.id));glyph.addEventListener('keydown',e=>{if(e.key==='Enter')systemFocus(s.id);});systemDOM.push({s,g,swirl,glyph});}}
function makeNodes(){$('bodies').innerHTML='';$('orbits').innerHTML='';nodeDOM=new Map();for(const n of model.nodes){let orbit;if(n.orbit){orbit=el('ellipse',{rx:n.orbit.radius,ry:n.orbit.radius*n.orbit.tilt,fill:'none',stroke:n.kind==='moon'?'#587187':'#73849a','stroke-opacity':n.kind==='moon'?'.25':'.32','stroke-width':'.7','stroke-dasharray':n.kind==='moon'?'2 4':''},$('orbits'));}
const g=el('g',{class:`body ${n.group==='solar'?'solar':''}`,'data-id':n.id,tabindex:0,role:'button','aria-label':`${n.id} ${n.label}`},$('bodies'));g.innerHTML=V.body(n,C.orbitIds.indexOf(n.id));const label=el('text',{x:0,y:n.r+24,'text-anchor':'middle'},g);label.textContent=n.id==='R02'?'RLEB · PPA':n.id;const name=el('text',{x:0,y:n.r+39,'text-anchor':'middle',class:'name'},g);name.textContent=n.label.length>17?n.label.slice(0,17)+'…':n.label;g.addEventListener('click',()=>{if(!dragging){selectNode(n.id);if(innerWidth<800)document.body.classList.add('panel-open');}});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});g.addEventListener('pointerenter',e=>tooltip(e,n.id,n.label));g.addEventListener('pointermove',moveTip);g.addEventListener('pointerleave',()=>{$('tooltip').hidden=true;});
if(!n.orbit&&n.kind!=='sun')d3.select(g).call(d3.drag().on('start',()=>{dragging=true;sim.alpha(.25);n.fx=n.x;n.fy=n.y;}).on('drag',e=>{n.fx=e.x;n.fy=e.y;}).on('end',()=>{n.ax=n.fx;n.ay=n.fy;model.anchors[n.id]={x:n.ax,y:n.ay,system:n.group};n.fx=null;n.fy=null;sim.force('anchorX').x(d=>d.ax);sim.force('anchorY').y(d=>d.ay);setTimeout(()=>dragging=false,50);}));
nodeDOM.set(n.id,{g,label,name,orbit,spin:g.querySelector('.spin')});}refreshLOD();}
function tooltip(e,id,label){$('tooltip').innerHTML=`<b>${esc(id)}</b>${esc(label)}`;$('tooltip').hidden=false;moveTip(e);}
function moveTip(e){const r=vp.getBoundingClientRect();$('tooltip').style.left=Math.min(e.clientX-r.left+15,vp.clientWidth-280)+'px';$('tooltip').style.top=Math.min(e.clientY-r.top+16,vp.clientHeight-95)+'px';}
function refreshLOD(){const k=zoom.k;for(const n of model.nodes){const d=nodeDOM.get(n.id);if(!d)continue;const isSelected=selected.type==='node'&&selected.id===n.id,major=n.kind==='sun'||n.kind==='galaxy'||n.orbit||isSelected;d.g.style.opacity=k<.22&&!major?'.48':'1';d.label.style.fontSize=Math.max(11,10/k)+'px';d.name.style.fontSize=Math.max(10,9/k)+'px';d.label.setAttribute('y',n.r+Math.max(24,18/k));d.name.setAttribute('y',n.r+Math.max(39,32/k));d.label.style.display=labelsMode||isSelected||(n.group==='solar'&&n.kind!=='moon'&&k>.35)||(k>1.1)?'':'none';d.name.style.display=(labelsMode&&k>.4)||isSelected||(n.kind==='sun'&&k>.3)?'':'none';d.g.classList.toggle('selected',isSelected);if(d.orbit)d.orbit.style.opacity=k<.22?'.4':'1';}for(const{s,g,glyph}of systemDOM){glyph.setAttribute('transform',`translate(${s.x},${s.y}) scale(${1/k})`);glyph.style.opacity=Math.max(0,Math.min(1,(.42-k)*6));glyph.style.pointerEvents=k<.35?'all':'none';g.style.opacity=zoom.k>.7&&s.id!=='solar'?'.25':'1';const tx=g.querySelector('.system-title'),st=g.querySelector('.system-subtitle');tx.setAttribute('font-size',Math.max(22,12/k));st.setAttribute('font-size',Math.max(13,8/k));tx.style.fontSize=Math.max(22,12/k)+'px';st.style.fontSize=Math.max(13,8/k)+'px';tx.style.letterSpacing=Math.max(2,1/k)+'px';st.style.letterSpacing=Math.max(1,.4/k)+'px';st.setAttribute('y',s.y-s.radius*.91+Math.max(28,18/k));}}
// Keep the central title from painting over an orbiting body; its inspector title remains available.
function declutterSunLabels(){for(const n of model.nodes.filter(n=>n.kind==='sun')){const d=nodeDOM.get(n.id);for(const label of [d.label,d.name]){if(label.style.display==='none')continue;const size=parseFloat(label.style.fontSize)||11,width=label.getComputedTextLength(),y=n.y+Number(label.getAttribute('y')),left=n.x-width/2,right=n.x+width/2,top=y-size,bottom=y+size*.25;const covered=model.nodes.some(p=>{if(!p.orbit)return false;const r=(V.visualBounds?.(p,C.orbitIds.indexOf(p.id))??p.r)+4;return p.x+r>left&&p.x-r<right&&p.y+r>top&&p.y-r<bottom;});label.style.visibility=covered?'hidden':'';}}}
function related(){if(routeMode==='none')return[];if(routeMode==='all')return model.edges;if(selected.type==='edge')return model.edges.filter(e=>e.id===selected.id);if(selected.id==='R02')return model.edges.filter(e=>['E02','E03'].includes(e.id));return model.edges.filter(e=>e.output===selected.id||e.inputs.includes(selected.id));}
function makeRoutes(){$('routes').innerHTML='';$('junctions').innerHTML='';$('ships').innerHTML='';visibleEdges=related();routeDOM=[];for(const e of visibleEdges){const neg=['refutes','limits'].includes(e.relation),open=e.relation==='open',color=neg?'#d28a88':open?'#ac95cf':'#759cb9',g=el('g',{'data-edge':e.id},$('routes')),paths=e.inputs.map(()=>el('path',{class:'route',stroke:color,'stroke-dasharray':neg?'4 5':open?'2 7':''},g)),out=el('path',{class:'route',stroke:color,'stroke-dasharray':neg?'4 5':open?'2 7':'','marker-end':`url(#${neg?'stop':'arrow'})`},g),hit=el('path',{class:'route hit'},g);hit.addEventListener('click',()=>selectEdge(e.id));const j=el('g',{class:'junction',tabindex:0,role:'button','aria-label':`${e.id} ${e.inputs.join(' 且 ')} ${e.relation} ${e.output}`},$('junctions'));el('path',{d:'M0 -10L10 0L0 10L-10 0Z',fill:'#0c1929',stroke:color,'stroke-width':'.8'},j);el('text',{'text-anchor':'middle',y:4},j).textContent='∧';j.addEventListener('click',()=>selectEdge(e.id));j.addEventListener('keydown',k=>{if(k.key==='Enter')selectEdge(e.id);});j.addEventListener('pointerenter',ev=>tooltip(ev,e.id,e.inputs.join(' ∧ ')+' '+e.relation+' '+e.output));j.addEventListener('pointerleave',()=>{$('tooltip').hidden=true;});const ship=el('g',{class:'route-ship',opacity:neg||open?'0':'1','aria-hidden':'true','data-ship-seed':e.id},$('ships'));ship.innerHTML=V.ship(e.id);
const dots=e.inputs.map(()=>el('circle',{r:1.8,fill:color,opacity:neg||open?'0':'.7'},$('ships')));routeDOM.push({e,g,paths,out,hit,j,ship,dots,neg,open});}updateRoutes();}
function path(c){return`M${c.a.x},${c.a.y}Q${c.c.x},${c.c.y} ${c.b.x},${c.b.y}`;}
function boundary(n,toward){const dx=toward.x-n.x,dy=toward.y-n.y,d=Math.max(1,Math.hypot(dx,dy)),r=(V.visualBounds?.(n,C.orbitIds.indexOf(n.id))??n.r)+5;return{x:n.x+dx/d*r,y:n.y+dy/d*r};}
function updateRoutes(){for(const r of routeDOM){const j=C.junction(r.e,model),o=model.byId.get(r.e.output);r.j.setAttribute('transform',`translate(${j.x},${j.y})`);let inputPaths=[];r.e.inputs.forEach((id,i)=>{const c=C.curve(boundary(model.byId.get(id),j),j,i),p=path(c);r.paths[i].setAttribute('d',p);inputPaths.push(p);const q=C.at(c,(clock*.11+i*.23)%1);r.dots[i].setAttribute('cx',q.x);r.dots[i].setAttribute('cy',q.y);});const c=C.curve(j,boundary(o,j),1),p=path(c);r.out.setAttribute('d',p);r.hit.setAttribute('d',inputPaths.join(' ')+p);const t=(clock*.08+C.hash(r.e.id)%100/100)%1,q=C.at(c,t),dx=2*((1-t)*(c.c.x-c.a.x)+t*(c.b.x-c.c.x)),dy=2*((1-t)*(c.c.y-c.a.y)+t*(c.b.y-c.c.y));const scale=Math.min(2,Math.max(.55,Math.min(.7,zoom.k*.5))/zoom.k);r.ship.setAttribute('transform',`translate(${q.x},${q.y}) rotate(${Math.atan2(dy,dx)*180/Math.PI}) scale(${scale})`);r.ship.style.display=zoom.k<.22?'none':'';for(const dot of r.dots)dot.style.display=zoom.k<.22?'none':'';r.j.style.opacity=zoom.k<.2?'.45':'1';}}
function nodeHref(n){return n.file?'../../research/'+n.file:null;}
function selectNode(id){const n=model.byId.get(id);if(!n)return;selected={type:'node',id};const related=model.edges.filter(e=>e.output===id||e.inputs.includes(id)),statuses=[...new Set(model.edges.filter(e=>e.output===id).map(e=>e.status))];const kind={sun:'主定理恒星',planet:'核心对象 · 行星',moon:'独立对象 · 卫星',body:'研究节点',hazard:'关系障碍 · 请核反驳范围',galaxy:'开放研究方向'}[n.kind];$('detail').innerHTML=`<div class="detail-id">${esc(n.id)} / ${esc(n.group.toUpperCase())}</div><h2 class="detail-title">${esc(n.label)}</h2><span class="tag">${kind}</span>${n.id==='R02'?'<span class="tag">局部 J_G · 有限长度</span>':''}<p class="detail-lead">${n.id==='R02'?'整个太阳系承载 RLEB–PPA 主链。八个行星是定义、条件与估计的入口；轨道远近不表示证明顺序。':n.orbit?'此物件对应真实图节点。公转表示视觉分组/导航轨道（父对象 '+esc(n.orbit.parent)+'），不声称父子推论；数学依赖须通过下方合取超边核对。':'此节点保留原图身份。所属星域仅用于导航，不改变对象、量词或证明状态。'}</p>${nodeHref(n)?`<a class="detail-link" href="${esc(nodeHref(n))}" target="_blank" rel="noopener">打开规范正文 <span style="float:right">↗</span></a>`:'<p class="tag">隔离演示节点 · 无规范正文</p>'}<div class="section-label">关联航道 <span>${related.length} 条真实超边</span></div>${related.slice(0,12).map(e=>`<button class="edge-card" data-edge="${esc(e.id)}"><b>${esc(e.id)}</b>${esc(e.relation)}<div>${esc(e.inputs.join(' ∧ '))} ${['refutes','limits'].includes(e.relation)?'⊣':'→'} ${esc(e.output)}</div><small>${esc(e.scope)}</small></button>`).join('')}${related.length>12?'<p class="detail-lead">其余关系可在搜索中按节点 ID 找到。</p>':''}<div class="section-label">证据原文 <span>不由天体造型推断</span></div><div class="definition">${statuses.length?statuses.map(esc).join('<br><br>'):'原图未给此节点单独状态。请查看规范正文与关联超边。'}</div>`;$('detail').querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>selectEdge(b.dataset.edge));makeRoutes();refreshLOD();}
function selectEdge(id){const e=model.edges.find(e=>e.id===id);if(!e)return;selected={type:'edge',id};$('detail').innerHTML=`<div class="detail-id">HYPEREDGE / ${esc(e.id)}</div><h2 class="detail-title">${esc(e.topic||'研究关系')}</h2><span class="tag">${esc(e.relation)}</span><p class="detail-lead">以下全部输入汇入同一 ∧ 枢纽。航船用于指示阅读方向，不表示证明已成立或算法正在迭代。</p><div class="section-label">全部合取输入 <span>${e.inputs.length} 项</span></div><div class="edge-inputs">${e.inputs.map((id,i)=>`${i?'<span>∧</span>':''}<button data-node="${esc(id)}">${esc(id)}</button>`).join('')}</div><div class="section-label">输出 / 被限制对象</div><div class="edge-inputs"><button data-node="${esc(e.output)}">${esc(e.output)}</button></div><div class="definition"><strong>适用范围 · 原文</strong>${esc(e.scope)}</div><div class="definition"><strong>证据状态 · 原文</strong>${esc(e.status)}</div><div class="definition"><strong>关系类型</strong>${esc(e.relation)}${['refutes','limits'].includes(e.relation)?'：不是正向证明；红色断续航道只标示原记录中的反驳或限制范围。':''}</div><a class="detail-link" href="../../research/HYPERGRAPH.md" target="_blank" rel="noopener">完整 Markdown 超边表 ↗</a>`;$('detail').querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>focus(b.dataset.node));makeRoutes();refreshLOD();}
function buildFleetGallery(){
const catalog=V.shipCatalog||[];
$('fleet-gallery').hidden=!catalog.length;
$('fleet-catalog').innerHTML=catalog.map((craft,i)=>`<div class="fleet-card"><svg viewBox="-30 -22 60 44" aria-hidden="true"><g transform="scale(.55)">${V.ship('gallery-'+i,{type:craft.id})}</g></svg><b>${esc(craft.name||craft.id)}</b><svg class="fleet-closeup" viewBox="-30 -22 60 44" aria-hidden="true">${V.ship('gallery-'+i,{type:craft.id})}</svg></div>`).join('');
}
function buildSystemList(){$('count').textContent=`${model.nodes.length} 对象 · ${model.edges.length} 关系`;$('system-list').innerHTML=model.systems.map(s=>`<button data-system="${s.id}"><span style="background:${s.color}"></span>${s.name}<small>${model.nodes.filter(n=>n.group===s.id).length}</small></button>`).join('');$('system-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{systemFocus(b.dataset.system);if(innerWidth<800)document.body.classList.remove('panel-open');});}
function render(){for(const {s,swirl,glyph}of systemDOM){glyph.setAttribute('transform',`translate(${s.x},${s.y}) scale(${1/zoom.k}) rotate(${clock*.5})`);swirl.querySelector('.field-spin').setAttribute('transform',`rotate(${clock*(.3+C.hash(s.id)%3*.15)})`);}C.updateOrbits(model,clock);if(sim.alpha()>.006)sim.tick();for(const n of model.nodes){const d=nodeDOM.get(n.id);d.g.setAttribute('transform',`translate(${n.x},${n.y})`);if(d.orbit){const p=model.byId.get(n.orbit.parent);d.orbit.setAttribute('cx',p.x);d.orbit.setAttribute('cy',p.y);}if(d.spin)d.spin.setAttribute('transform',`rotate(${clock*(n.kind==='sun'?1:4)})`);}declutterSunLabels();updateRoutes();}
function loop(t){const dt=last?Math.min(.05,(t-last)/1000):0;last=t;if(running)clock+=dt*speed;render();frame++;requestAnimationFrame(loop);}
function resizeStars(){const c=$('stars'),r=devicePixelRatio||1,w=vp.clientWidth,h=vp.clientHeight;c.width=w*r;c.height=h*r;const ctx=c.getContext('2d');ctx.scale(r,r);ctx.fillStyle='#040914';ctx.fillRect(0,0,w,h);let rand=d3.randomLcg(.618);for(let i=0;i<Math.max(300,w*h/1700);i++){const x=rand()*w,y=rand()*h,z=rand(),rr=z>.97?1.2:rand()*.7+.12;ctx.globalAlpha=.14+rand()*.55;ctx.fillStyle=i%7===0?'#84abce':'#d0daec';ctx.beginPath();ctx.arc(x,y,rr,0,Math.PI*2);ctx.fill();if(z>.994){ctx.globalAlpha=.16;ctx.fillRect(x-4,y-.25,8,.5);ctx.fillRect(x-.25,y-4,.5,8);}}ctx.globalAlpha=1;}
function setGraph(graph){C.validate(graph);const previous=model;model=C.make(graph,previous);sim=C.simulation(model).alpha(.48);clock=model.time;makeBackdrop();makeNodes();buildSystemList();if(!model.byId.has(selected.id)&&selected.type==='node')selected={type:'node',id:model.byId.has('R02')?'R02':model.nodes[0]?.id};if(selected.type==='node')selectNode(selected.id);else if(model.edges.some(e=>e.id===selected.id))selectEdge(selected.id);else selectNode(model.byId.has('R02')?'R02':model.nodes[0]?.id);render();return {nodes:model.nodes.length,edges:model.edges.length};}
function growth(){demo++;const graph=JSON.parse(JSON.stringify(model.graph)),parent=selected.type==='node'?selected.id:'R01';for(let i=0;i<8;i++){const id=`DEMO-${demo}-${i}`;graph.nodes.push({id,label:`沙盒新增对象 ${demo}.${i}（非数学命题）`,file:''});graph.edges.push({id:`DEMO-E-${demo}-${i}`,topic:'隔离布局测试',inputs:i?[parent,`DEMO-${demo}-${i-1}`]:[parent],output:id,relation:'demo-only',scope:'虚构布局压力测试，不写入 research/graph.json',status:'sandbox-only'});}setGraph(graph);$('demo-banner').hidden=false;$('clear-demo').hidden=false;const n=model.byId.get(`DEMO-${demo}-0`),p=model.byId.get(parent);for(const q of model.nodes.filter(n=>n.id.startsWith(`DEMO-${demo}-`))){q.group=p.group;q.ax=p.x+100+Math.cos(C.hash(q.id))*100;q.ay=p.y+100+Math.sin(C.hash(q.id))*100;q.x=p.x;q.y=p.y;model.anchors[q.id]={x:q.ax,y:q.ay,system:q.group};}sim.force('anchorX').x(n=>n.ax);sim.force('anchorY').y(n=>n.ay);sim.alpha(.7);camera(p.x+80,p.y+50,1.35);toast('8 个隔离测试对象正在由排斥力、碰撞力与锚点力展开。原数学图不变。');}
function syncMotion(){document.body.classList.toggle('motion-paused',!running);$('motion').textContent=running?'Ⅱ':'▶';$('motion').title=running?'暂停公转与航行':'继续公转与航行';$('motion').setAttribute('aria-pressed',String(!running));}
function motion(){running=!running;syncMotion();}
$('home').onclick=solar;$('overview').onclick=overview;$('fit').onclick=overview;$('chain').onclick=()=>{solar();routeMode='related';$('routes-toggle').textContent='航道：关联';selectNode('R02');};$('zoom-in').onclick=()=>zoomBy(1.35);$('zoom-out').onclick=()=>zoomBy(1/1.35);$('motion').onclick=motion;$('speed').onclick=()=>{speed=speed===1?3:speed===3?.35:1;$('speed').textContent=speed+'×';};$('routes-toggle').onclick=()=>{routeMode=routeMode==='related'?'all':routeMode==='all'?'none':'related';$('routes-toggle').textContent='航道：'+({related:'关联',all:'全部',none:'隐藏'}[routeMode]);makeRoutes();};$('labels-toggle').onclick=()=>{labelsMode=!labelsMode;$('labels-toggle').textContent='标签：'+(labelsMode?'全部':'自动');refreshLOD();};$('growth').onclick=growth;$('clear-demo').onclick=()=>{setGraph(BASE);demo=0;$('demo-banner').hidden=true;$('clear-demo').hidden=true;solar();toast(`已回到原始 ${BASE.nodes.length} 个节点与 ${BASE.edges.length} 条超边。`);};$('close-panel').onclick=()=>document.body.classList.remove('panel-open');$('mobile-detail').onclick=()=>document.body.classList.add('panel-open');
$('search').oninput=()=>{const q=$('search').value.trim().toLowerCase(),nodes=model.nodes.filter(n=>(n.id+' '+n.label).toLowerCase().includes(q)),edges=model.edges.filter(e=>(e.id+' '+e.inputs.join(' ')+' '+e.output+' '+e.topic).toLowerCase().includes(q));$('search-results').hidden=!q;$('search-results').innerHTML=nodes.slice(0,18).map(n=>`<button data-n="${esc(n.id)}"><b>${esc(n.id)}</b>${esc(n.label)}</button>`).join('')+edges.slice(0,8).map(e=>`<button data-e="${esc(e.id)}"><b>航道 ${esc(e.id)} · ${esc(e.relation)}</b>${esc(e.inputs.join(' ∧ '))} → ${esc(e.output)}</button>`).join('');$('search-results').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.n)focus(b.dataset.n);else{selectEdge(b.dataset.e);const j=C.junction(model.edges.find(e=>e.id===b.dataset.e),model);camera(j.x,j.y,.85);}$('search-results').hidden=true;$('search').blur();});};document.addEventListener('keydown',e=>{if(e.key==='/'&&e.target.tagName!=='INPUT'){e.preventDefault();$('search').focus();}if(e.key==='Escape'){$('search-results').hidden=true;document.body.classList.remove('panel-open');}if(e.code==='Space'&&e.target===document.body){e.preventDefault();motion();}});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches&&running)motion();});window.addEventListener('resize',resizeStars);
buildFleetGallery();makeBackdrop();makeNodes();buildSystemList();selectNode('R02');for(let i=0;i<220;i++)sim.tick();resizeStars();solar();syncMotion();requestAnimationFrame(loop);
window.cosmos={get graph(){return JSON.parse(JSON.stringify(model.graph));},get anchors(){return JSON.parse(JSON.stringify(model.anchors));},get state(){return{time:clock,running,speed,frames:frame,nodes:model.nodes.length,edges:model.edges.length,selected:{...selected},engine:'d3-force 3.x / D3 7.9.0'};},get positions(){return model.nodes.map(n=>({id:n.id,x:n.x,y:n.y,kind:n.kind,parent:n.orbit?.parent}));},updateGraph:setGraph,selectNode,selectEdge,focus,overview,solar,pause(){if(running)motion();},resume(){if(!running)motion();},growth,reset(){setGraph(BASE);demo=0;$('demo-banner').hidden=true;$('clear-demo').hidden=true;solar();}};
})();
